fix(tools): disable clang-tidy static assert check
This patch disables clang-tidy checks which suggest replacing calls to
assert() with static_assert():
lib/attestation/src/attestation_key.c:75 error: found assert() that
could be replaced by static_assert()
        assert(SIMD_IS_FPU_ALLOWED());
        ^~~~~~
        static_assert               , ""

The suggested fix is not possible because this will be a runtime check
when RMM_FPU_USE_AT_REL2 is enabled.

Signed-off-by: Chuyue Luo <Chuyue.Luo@arm.com>
Change-Id: Iedeafd94581959438e40cd58ae8488862d7ca5dd