fix(lib): clang-tidy implicit widening errors
This patch fixes errors from the clang-tidy
bugprone-implicit-widening-of-multiplication-result check:
- lib/xlat/src/xlat_high_va.c:111: error: result of multiplication in
type 'unsigned int' is used as a pointer offset after an implicit
widening conversion to type 'size_t'
- lib/xlat/src/xlat_tables_core.c:54: error: result of multiplication in
type 'unsigned int' is used as a pointer offset after an implicit
widening conversion to type 'size_t'

Signed-off-by: Chuyue Luo <Chuyue.Luo@arm.com>
Change-Id: Ieed636eee803dd18b72126757fffd29cf10e609e